name: Update Notebook

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    branches:
      - master

jobs:
  with-papermill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2
        with:
          repository: 'casca/covid19-notebook'
          ref: master
          persist-credentials: true
      - name: Update with papermill ğŸ“„
        uses: casca/papermill-docker-action@master
        with:
          notebook: charts.ipynb
      - name: Commit files ğŸ“©
        run: |
          git config --local user.name "casca"
          git config --local user.email "8927157+casca@users.noreply.github.com"
          git add charts.ipynb forecasts.png grid.png heatmap.png
          git commit -m "Update notebook and charts"
      - name: Push changes ğŸš€
        uses: ad-m/github-push-action@master
        with:
          repository: 'casca/covid19-notebook'
          github_token: ${{ secrets.GITHUB_TOKEN }}
