name: Update Notebook

on: push

jobs:
  with-papermill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout üõéÔ∏è
        uses: actions/checkout@v2
        with:
          repository: 'casca/covid19-notebook'
          ref: master
          persist-credentials: true
      - name: action
        uses: casca/papermill-docker-action@master
        with:
          notebook: charts.ipynb
      - name: Commit files
        run: |
          git config --local user.name "casca"
          git config --local user.email "8927157+casca@users.noreply.github.com"
          git charts.ipynb
          git commit -m "Update lighthouse report for casca.dev"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: 'casca/covid19-notebook'
          github_token: ${{ secrets.GITHUB_TOKEN }}
